server:
    port: 8761
eureka:
    instance:
      hostname: localhost
    server:
#    # 自我保护模式关闭
#        enable-self-preservation: false
#    # 清理间隔（单位毫秒，默认是60*1000）
#        eviction-interval-timer-in-ms: 2000
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/